---
# Source: books/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: books
  labels:
    helm.sh/chart: books-0.1.0
    app.kubernetes.io/name: books
    app.kubernetes.io/instance: bookapp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: books
    app.kubernetes.io/instance: bookapp
