---
# Source: order/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    helm.sh/chart: order-0.1.0
    app.kubernetes.io/name: order
    app.kubernetes.io/instance: bookapp
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: order
      app.kubernetes.io/instance: bookapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order
        app.kubernetes.io/instance: bookapp
    spec:
      serviceAccountName: default
      securityContext:
        {}
      containers:
        - name: order 
          securityContext:
            {}
          image: "tntk/prod/order:temptag"
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c"]
          args: ["alembic upgrade head && uvicorn order.main:app --host 0.0.0.0 --port 8001 --reload"]
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /order/metrics
              port: http
          readinessProbe:
            httpGet:
              path: /order/metrics
              port: http
          resources:
            {}
          volumeMounts:
          - name: bookapp-configmap
            mountPath: /code/.env
            subPath: .env
      volumes:
      - name: bookapp-configmap
        configMap:
          name: bookapp-configmap
